name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: copy file via ssh password
      uses: EC528-ML-RealEstate/ML-Services@main
      with:
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*"
        target: "/srv/ML"
